addons:
 sonarcloud:
 organization: “iberganza”
 token: “9c3b8a87656674c507fab81e3a868edce43af78e”
script:
 # the following command line builds the project, runs the tests with
coverage
 # and then execute the SonarCloud analysis
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
org.jacoco:jacoco-maven-plugin:report install sonar:sonar